### ISSUE TITLE
Give us a a button to automatically pin reset

### ISSUE THREAD

**Issue by darkpony345** [emmVRC/emmVRC-Risky-Function-Request#105]
There needs to be a button that automatically does it for you and the VR chat game for the mod if you forget your things you can automatically push a button and it can automatically do it for you from the bot or something else that would be cool to add and another thing a protection for your accounts and your PIN number make it where hackers or anybody else can not steal your stuff for hack into your stuff by your PIN number and I would like a ban button and an unban button and a white list button so I can see my ban list on The mod itself so if people are being toxic I can ban them to blacklist and whitelist them if they are my friends I don't want no toxic people joining me and a button to allow you to have more avatars and go past VR Plus really awesome 👍😎 and while you're in the game let's have a off-branch button where you can connect your Discord and all of your other social medias and one last thing a mini web browser button so we don't have to leave the game we can also have a mini web browser of our own call it the VRC browser button where you can browser anything and anything you want while you're in the game and that is it

**Comment by darkpony345** [comment]
For whoever wants to add me go to my YouTube channel Darkness parasite

**Comment by Janni9009** [comment]
Okay, to begin: This is the wrong repo. Feature requests go [here](https://github.com/emmVRC/emmVRC-Public)
Then, your pin **IS** what protects malicious actors from messing with your emmVRC Data if your VRC account gets breached.
We will not be adding moderation features to emmVRC, VRChat has plenty of options for you, such as (in public vote-)kicking and reporting users, or going to a new/private instance with your friends
You can link your socials in your VRChat Bio already, not gonna add that.
And for a web browser, in VR just use an overlay such as Steam/Oculus's Dashboards (literally included with your VR Runtime), or all available on Steam: XSOverlay, OVRToolkit or Desktop+; as for desktop, just alt-tab or get a second monitor.
Also, deleted the second comment due to self-advertising.
