### ISSUE TITLE
[WHITELIST] Snowdin Town - Grillby's Le Flambeau

### ISSUE THREAD

**Issue by Natzo111** [emmVRC/emmVRC-Risky-Function-Request#14]
A developing world with several months of work poured into it in attempts to make an enjoyable pseudo-RP experience with public instances. Considering what the UT community attracts, it can get somewhat chaotic when younger people fly and no-clip around the world while grabbing and throwing props. Whitelisting this world will ease the stress and workload of the RP employees.

**Comment by Hordini** [comment]
Denied ❌

Given your explanation, I assume you meant to request a "blacklist". I've changed the title to reflect this.

While I understand the reasoning for your request, it appears that Risky Functions do not allow users to gain an advantage over other users, or invade other's privacy, in this world. These are the main reasons we restrict Risky Functions in worlds. I personally recommend conducting RP sessions in private instances, so as to have more control over users.

However, we do comply regardless of these reasons if contacted by the world author. If they would like Risky Functions to be disabled in their world, they may contact me any time at Hordini#0526.

Keep in mind, if they attempt to contact me, I will most likely miss friend requests if they send one. If we share no mutual servers, let me know if they send a friend request, and I'll be sure to keep an eye out for it. Otherwise, my DMs are always open for discussion.
