### ISSUE TITLE
[WHITELIST] Chill Home

### ISSUE THREAD

**Issue by forever-and-a-day** [emmVRC/emmVRC-Risky-Function-Request#58]
https://vrchat.com/home/world/wrld_1b482eca-bede-4de8-88a8-bbb6ca7e24cd
No private rooms, only games are 8 ball.

**Comment by Louka3000** [comment]
Yes, please! My friends and I hang out a lot in this world and since I'm using a small avatar, not being able to fly is very inconvenient. The "games" tag is because of the pool table. There is a "private" room as the description states, but it's the same kind of "private" room as the one in Furry Talk and Chill (a room hundreds of meters away from the spawn that can be accessed by simply clicking on a hidden button, no lock or password)

**Comment by Hordini** [comment]
Accepted ✔️
