### ISSUE TITLE
no serealization switch

### ISSUE THREAD

**Issue by Fennieluv** [emmVRC/emmVRC-Risky-Function-Request#70]
add a no serealization switch for anti crashing and anti exploit events making it impossible to receive events from other players and thus not being possible to be teleport exploited-crashed from abusive players

Generally a Mayday button for extreme scenarios.

**Comment by Fennieluv** [comment]
Q: What it does? A: It disallows the client to receive any event codes and trigger codes Basically freezing your game and making it think youre pinging but not sending back any data

Q: Can it be used to harm lobbies and gameplay? A: Simply put No there are no known ways to exploit it in such way to harm since it wont recieve any game changes only you showing players move and disallowing you to make any movement ingame and acticate triggers such as doors and buttons

Q: How the game will benefit from it? A: it will allow you to stop any incoming event codes from the map/players thus disallowing them to change into an avatars or make any gestures and avatar 3.0 action based animations and disarming crasher avatars or event based exploit hacks

Apologies for quircky english

**Comment by loukylor** [comment]
I don't see how this could help against crashers. If someone wanted to crash you and you knew before hand, then just hide their avatar. If you didn't know before hand then how would this help?

Also, photon based exploits could be stopped by this. But, in order to do literally anything, you would have to turn back on photon. If you wanted to leave, you would have to turn on photon in order for the game to disconnect you properly and for photon to actually send you to the correct room. On the topic of disconnections: you WILL get disconnected by photon if you try this. You are sending literally no data to photon, meaning it will assume your client has died and you will be booted by photon after a ~minute or so of being in this state.

Lastly, you will be able to move in this state. You will also be able to interact with doors and things. This is extremely dangerous, as it allows you to literally stop moving to everyone else, then suddenly teleport to where you want to be. This could easily be abused in many game worlds, and in certain club worlds could be used to get into private rooms. And yes, you actually are able to move in this state. I will not argue this fact.

**Comment by loukylor** [comment]
Right, I just realized that this is the wrong repository for this. This repository is meant for blacklisting/whitelisting risky functions in worlds, not feature requests.

**Comment by rakosi2** [comment]
This is the wrong repository, The correct repository would be https://github.com/emmVRC/emmVRC-Public/issues
